[ci] fix flutter analyze which break on info

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,7 +50,17 @@ jobs:
         working-directory: ${{ matrix.package }}
 
       - name: Analyze
-        run: flutter analyze
+        run: |
+          OUTPUT="$(flutter analyze)"
+          echo "$OUTPUT"
+          echo
+          if grep -q "error •" <<< "$OUTPUT"; then
+              echo "flutter analyze found errors"
+              exit 1
+          else
+              echo "flutter analyze didn't find any errors"
+              exit 0
+          fi
         working-directory: ${{ matrix.package }}
 
       - name: Run tests
